### ISSUE TITLE
Multi-language / translations

### ISSUE THREAD

**Issue by ElDavoo** [AkashRajpurohit/howtoprofessionallysay#15]
**Is your feature request related to a problem? Please describe.**
If you're not english you have to translate everything

**Describe the solution you'd like**
Multi-lang support

**Describe alternatives you've considered**
nothing

**Additional context**
no

**Comment by AkashRajpurohit** [comment]
It is a good feature to have and totally make sense for this app. I feel this might require help from people to provide valid translations for the existing and upcoming dataset as well.

For starters these could be some of the translations that could make sense (of course not all and maybe some other can be added if there are people to provide translations for it)

![image](https://user-images.githubusercontent.com/30044630/171132144-7a8101d2-822c-4376-a705-8744ad10a038.png)

If there are people around who would like to help in this then you can let me know here, once I have some confirmations around it, I can start looking into the code part of the things to hook up translations to the app.

**Comment by ElDavoo** [comment]
count me in for italian

**Comment by pavelloz** [comment]
I can try with polish :)

**Comment by Grip** [comment]
> count me in for italian

Plus one.

**Comment by canongigue** [comment]
If you want Thai (which is also one of the hardest regarding this and the culture), let me know.

**Comment by ayub-kokabi** [comment]
I'm honored to translate it into [Persian/Farsi/فارسی](https://en.wikipedia.org/wiki/Persian_language).

**Comment by okalil** [comment]
Hey, I can help with Brazilian Portuguese.
