### ISSUE TITLE
Fonts optimization

### ISSUE THREAD

**Issue by pavelloz** [AkashRajpurohit/howtoprofessionallysay#17]
I recommend (for performance reasons) to optimize fonts and serve modern format.

I wrote a little bit on th subject here: https://pavelloz.com/blog/google-fonts-optimization/

**Comment by AkashRajpurohit** [comment]
So when you say serve modern format, you mean to try and use woff or woff2 formats? I think currently I am loading fonts from local file, and they are of OpenType format.

**Comment by pavelloz** [comment]
Yes, font-face definition can accept multiple formats, I think serving woff2 + woff/otf/ttf means covering 99% browsers. only woff2 is not supported everywhere yet, basically.

But apart from using better format you could also optimize for characters used on website, to make the font itself much smaller.

More about support: https://caniuse.com/woff2
https://caniuse.com/woff
https://caniuse.com/ttf

**Comment by AkashRajpurohit** [comment]
Does make sense to add this for performance reasons, I can take a look at it or if you want to send a PR for this then I'm happy to take a look at it :)

**Comment by pavelloz** [comment]
Sure, ill open PR in couple of days :)
