### ISSUE TITLE
Poor wording

### ISSUE THREAD

**Issue by markasoftware** [AkashRajpurohit/howtoprofessionallysay#22]
"As per my prediction, this outcome does not come as a surprise."

As a native English speaker, this sentence sounds very unnatural. It is a "dangling modifier" (or similar); it sounds like the prediction you made was that the outcome would not be a surprise. But in fact you're trying to say that you predicted the outcome.

Better alternatives include:
* "This outcome does not come as a surprise."
* "This outcome agrees with my earlier prediction."
* "Seeing as it agrees with my earlier prediction, this outcome is not a surprise."

**Comment by AkashRajpurohit** [comment]
Thank you for sharing your insights, please feel free to send a PR by adding these in the [alternativeAnswers for this statement](https://github.com/AkashRajpurohit/howtoprofessionallysay/blob/main/content/qna.ts#L22). I'll be happy to take a look at it 😊
